# -*- coding: utf-8 -*-
"""Исключения и обработка ошибок_DZ_6_с ошибками.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18scbkPNTEr1ndeFVaZVQ4PG3uslrbyqc
"""

# 3.1 Одна функция
# данное решение с одной функцией. В случаи неверного формата возвращается верная ошибка, как я и предполагаю.

import datetime


def data_list(start_d, end_d):

    date_list = []
    try:
        start_date_dt = datetime.datetime.strptime(start_d, '%Y-%m-%d') - datetime.timedelta(days=1) #  нашел только такой вариант как включить первую дату.
        end_date_dt = datetime.datetime.strptime(end_d, '%Y-%m-%d')
        while start_date_dt < end_date_dt:
            start_date_dt += datetime.timedelta(days=1)
            data_str = start_date_dt.strftime('%Y-%m-%d')
            date_list.append(data_str)
        return date_list
    except ValueError:
        return f"Неверный формат даты - {date_list}"

start_date = '2024-03-25' # Выбран неверный формат данных!
end_date = '2024-04-02'

data_list(start_date, end_date)

# 3.2 Реализация двух функции.
# Выбираю специально неверный формат даты. Тогда почему возвращается подобная ошибка: TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
# Я ожидал что будет возвращено как 'Ошибка формат даты', которую я указал в функции correctDate(date)
# Поэтому что бы функция возвращала пустой список я во вторую функцию добавляю ошибку не ValueError, а TypeError!
import datetime


def correctDate(date):
    """
    Функция возвращает формат '%Y-%m-%d' в формат datetime.datetime
    """
    try:
        return datetime.datetime.strptime(date, '%Y-%m-%d')
    except ValueError:
        return 'Ошибка формат даты' # ожидаю что будет именно это сообщение!


def date_range(start_date, end_date):
    d_list = []
    """
    Функция возвращает список дат от start_date до end_date
    """
    try:
        s_d = correctDate(start_date) - datetime.timedelta(days=1) #  нашел только такой вариант как включить первую дату.
        e_d = correctDate(end_date)
        while s_d < e_d:
            s_d += datetime.timedelta(days=1)
            d_list.append(s_d.strftime('%Y-%m-%d'))
        return d_list
    except TypeError:  # приходится ставить ошибку TypeError чтоб работала функция, но тогда почему не срабатывает первая функция не выводя ошибку :
        return d_list


start_date = '2024-03-25'
end_date = '2024-04-02'

date_range(start_date, end_date)